language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8
before_install:
- git checkout main
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password: pypi-AgEIcHlwaS5vcmcCJGE4MTQ0ZDk5LWYwYTgtNDA2Ny05NzAyLWM2OWI3YWYyN2M5NgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgCfmgtb4NQIMeZO93yioz9PXWKGsS7M5egv9hku_hzB0
  distributions: sdist
  skip_existing: true
  skip_cleanup: true
  on:
    repo: tsukada-cs/pyfld
    branch: main
    python: 3.8
dd:
  secure: A5UgqVsF3MX8VQdIufndSLZiAZBO2ZGFPgMArV/veob9pylqET2TEBPmewSSjVnYNFzxQtgIXz0ZkQlkqtpNeT5yh6pErNQsztVXU18oda9LftUlijIPuolOR2RDv6KZHKdqcxXfTzGgn+oFSKW9juzcJJ14nCkWoFU8mwTWrlldz87cnr5VPbGkioXXV7FfeG/XnKEPOD0LRPB4/ZbB96ztKFFSFWwmL5z6gOp6HFKVgQhn2tMG6axJH+vQgvD5JLgPnYL49GhpzXNdpX7jCQAmMKwfFVy9voBpqyoJGy2BeoUd/7+C7JMRESKjsPB9D8UFFiIboKsrwQfn8hqhqGCSJfyKpLoDdpbg4dE02malBEbUm3uOHaR235jfZHqpQI77kseFXXz2KVJhLDamj2CPd3VAB6W8CUaUxMPfwISuVhGcxNXSLrZNJ4LNOzdPhla8JNYqW2KfmXgO5cBACzhXGb0UmfRkVr+ReJ+WootxbcuztqSJML8eA3h/rpR9TvU3DpFZn2caea/TFSybP+bRCS+mPpdCXG7qfHjEFd1IP3v2BGlpuxhrG4wway8ciX5lSb5GUlu1d3V1P5C33Etc4PLeZ/v3CsZWDfasTLxjoQjwAnqfIPQFZkkK4IyEuy5fclg3F5YXe0KRKpPMD1vzPBdrkUNIUtQ9dWMdx78=
