language: python

python:
    - 3.6
    - 3.7
    - 3.8

before_install:
    - pip install coveralls pytest-cov

install:
    - pip install -e .

script:
    - pytest --cov=pyfld pyfld/tests
    - coverage run -m pytest pyfld/tests

after_success:
    - coveralls