language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8
before_install:
- git checkout main
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: tsukada-cs
  password:
    secure: QRagv2JPvlkAoUq9+UxU+VNBy84x5jbLdgqbGNL5T+QlCQ3GBVJj85VDCobU6cDnAshCXMOCoJKBiWg0EnN+OzV/DLkEAD/nwcHD3Njle64WS3HMlA7xM+MAP8u8+ZxQZFyNE3dGpwEfR7cbq9kouMlLcJxTvdHMLf3SaQThBmzzhkCveUyx6Zef9kcjcwI7xuURFcYpAW7L1mppYFgq+mNpXxVFl8uid5YvPDtZ7Gq/Z+bxL1mFJFCzC59O9mmrjkIMGN+TpG82+i7AzxsXXG3A9rxxXVXhc02RX1l1DTEytyrd+nrPyck58cOWK6An1iS19mkHAXIYFKoSoSL07ckXdSXe9ST73Ra29QcOhrQOWlfkw9gv11c0hTbPv9E7WtGiN2jDBnaKFFLZuW4RS9WCQ6/XWhtHvZ31vKv88pMnppZ3HHzyRj45ZpsWq7ihizrcY1S/Yehq3liRejhwh8I2qqt7MhkY7QAW42bOqbGJZRI3LE7pc+O0Fd1J4/7JTAYpl4+/fG5xec9P5nL9HJKCG2vtFzkyrnfq2r5+HGTDpNA8JN1bg6oj+qYhXZOTCqKyScXDbAgmWSZW1DjsLjo9YsiIVAeZtpH3B8ZsP3m+bZP2Dz3JzjMEHfMtBezLHIu++4c7/te5kWaiBt9U6jyxdNt8b1erTWb7fbiLNAs=
  distributions: sdist
  skip_existing: true
  on:
    repo: tsukada-cs/pyfld
    branch: main
    python: 3.8
