language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8
before_install:
- git checkout main
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: CRITCv4ZosqM2v+3/U4NTeM+Ibx3xKdDU9rDAPjVREHKsQzzyrr/5Jh4SEsdbo2j0a9TPKt1pqU5BjPJM2PqwarqXgOCHB1IJkelu15rildRiTtDPrJBR2H2/dTcguNLXngdB7KSl7GpaXO/7RSFJt62mtEO4LHLWltgDQq4kAwxyUlLKN9F5WL2TULLLxRH17CTpiawdyYOnzf+KPtd3Cfly7Hons0vvWQArLGRWxhwq0enlp3xGiSZqfw4eaBGYNwer9Ojztyz2yjkduvMpNHyYgpKHjBxFcH+Bblj8CsBmqJce8LCDGx0isd+KNIAWUl7j8b8JQg6zbmVzI0+zsDUxwvzEM+7+e2llGCB3f5ORUybfdJMSzOd5PCf1uqqRPDawF2YTrSiQc0J7nuLCIfpkT94WzMVKRJmJjjo3K0ZvmCS+SX19+jnIo4eJR+CUAT4gOw61a1cF2NYntEYP3RosxveYeMRLY5Hx/o+SOjjx86/7HigUnHpuNO4ON0MgqaGXScf5UI1JVtFmbOAUBsRELJmbvU+VMkTi6X4pmvnQen5RNQcw//B6KSonLeI6e3IDxo2ADf1i6mUBeda2Pz/OKkHqmA/bgJbLz+2JPA7N4DJWPy6BfGXjq1Nu/3K5C9icsEu4F30Pr/H/UiZVROiyhBaosajXxDTjTgnl6I=
  distributions: sdist
  skip_existing: true
  on:
    repo: tsukada-cs/pyfld
    branch: main
    python: 3.8
