language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8
before_install:
- git checkout main
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: Ae/PNNg/ZwpZyS3GfqCiQldlZQAErXvk1WZgXjULAgyQGY5pvwONcg7waVj3kdZYY2Bx2082oWT14ssgy6sYsgsUf5uTeKzhCwjKGdmU5W4cv97bEfDcPCIHj39MVGu1BKUieL+12eBx/pD6XfsUJ2syJODGeE0PiIQczdYuYg4jjYGsylvUKUIfNJa9+3h5sE+sEK8b2B15Jr2tu0NW2ZzPxNppvrgp6i0dlCqQ4+8ZRd1Q3BjK+evXFMg2FjbkbpHJZHHjH8pZmUF6MGntAsil3Bm1ZkXsRUNVuFTLL/WOhFw19UDiO/5CbQlsH/1KE1oyulAgfQ5pZbwYiCi1D9j3el3KOdziDhtMB/CT9tdCSqVLvi3AnTI+g/Q1jHqj1vvI2HeS/LeFMeBdIQNk6eBosIvApxEpQxYstOk+mEq6XHCjaF33HmQR4FnLR1oB6aojdsOxTB+Nu5/JC3EiEsNuVwFGgJl6Y5otV5ge2IVYR9htxsrOREVp8ZGbA5LmhRwQHsSX4FUTI3elHoUO92N2zTX8ympD3SbzBrLJTFRtzncB44ZNmwQbY9Mb4sJVwEsLAUcVf3FCHh7DKA7f8A5rj1cFw4Tk3qsEjjNLzLX36V84Y9ejncq73ICemduU1QfvE/346GlRK6chjlmEer599SK7pBMp9AWK5KQBh9E=
  distributions: sdist
  skip_existing: true
  on:
    repo: tsukada-cs/pyfld
    branch: main
    python: 3.8
