language: python
python:
- 3.6
- 3.7
- 3.8
before_install:
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: tsukada-cs
  password:
    secure: CTCGdAt2Bwm4eyW5F/JdXwvo+wevw2RQTLdWZhSPn0iMX/bXbfsoJ8FT4Gt7kcVYBbxkD7HJOpM3gWobeq4WvHBQnHpG8/RN+k3CL3yJ0ntllrKvEDtLJ0xtup2+inZ0AEO2zyg2SLQKL8gnwvqKKLGw6JE5XlKqahlA4Q/W4VatDPcWof85rBQIER1jOv8LysZ6QpfeVZJ5qw1fRnRRwRCEUy7tj/JItWcoR0RK4E0EMMAkfEfDenap97Hz5jBp6zpnGgFcT+Hs8gYVwzfl1SN7au8GedQExuA52ZppM1pcvJF9T3W9HIIb7BcNmStYZqiu/FjLQMfnLRxtmks4KGe+bEt8WdOtlW7jVowDsT7TqrqzAfrt2hccx+zb0RGsSgEASon9MZrRXZlwq2h9uinOA/Zt/Z6cLQ94IJ7ayfus8aVRFXX++Y4RLOJBGpNVXYCbr5eBbTaFb9ErEQaV5BxQ4w/MBQThT63lp/8lzEyRK78i8K4ocfAVaiZmVY5Ze6+NCtw8b2xDXIHOtA/ZStU8+/RE71PHJuHCJR4jXw0WWJZgr/vq0+wM52blaTf04bidBioYEnibe0QfdSlgIm4SzOOS4L/nLn/CLAyrPK/9OrJshsxLSH/EGYXevqlG/NgqpZIW2TXH3/15/TACbxU79BgNC5UNx3NAydrIN6g=
  on:
    tags: true
