language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8
before_install:
- git checkout main
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: tsukada-cs
  password:
    secure: iU4/17V89NzTp+e56ACN4pahYS97UpBlXubYxcFzUBXekDc8e5YJKcKBUOqjWGKDmd+lEx0gpq/HonyXPtfsts1CS4XWMuTVXMeuwp9Em0d3Z69n1scV0UJXH6TR0xAuiL8VsDitJJokH6SifJF13dzYO3OnhGrmwVSyFTzru405RUObdykVNo/WcVBcyJKzzbbv/rvVQKkI/9+n44qpR2V+w/mBrQi2Jsxgm7ZrOxWmQ91T0Ca3wgQJO8qiCmRx6KqK7bNQbvLp0KjU3jJjsWOqWOZv7QPiEME9+alR59b2h/rj1w6ycbddusJPhz0317t6aNyArcQImowz8VFyvK2ORRYQUCz+r7tyOru9tNsv2b+CktlPsa+ldENqh3gq/csUajnddtEk0xeQTRGDCPdrRbYbtgCPsvQMhPyhpTm5reXKfsbNd/PcIRH/O0rdghf+TcP299iI2avso8fp7iDnXQKqWlmEoxoPQ/9H0qcyvhWA7XT7IytPz6oWeko8l/nmKJ1QHtPd/jIDP+MjhEjnQIJAxwT/JFtyFw8Crnnhp4iqarNVDzPE5tloyYlX1cqVJmovvlXchgoOp6GGGXsONhhUYTdJ8oCJZ+PfQEYU+C8In9DyySfEutUiFOYKuvywT2SDXdSZ+1F8P0z2FyzEqn+IIjpOjIjyJU1wZLE=
  distributions: sdist
  skip_existing: true
  skip_cleanup: true
  on:
    repo: tsukada-cs/pyfld
    branch: main
    python: 3.8
dd:
  secure: A5UgqVsF3MX8VQdIufndSLZiAZBO2ZGFPgMArV/veob9pylqET2TEBPmewSSjVnYNFzxQtgIXz0ZkQlkqtpNeT5yh6pErNQsztVXU18oda9LftUlijIPuolOR2RDv6KZHKdqcxXfTzGgn+oFSKW9juzcJJ14nCkWoFU8mwTWrlldz87cnr5VPbGkioXXV7FfeG/XnKEPOD0LRPB4/ZbB96ztKFFSFWwmL5z6gOp6HFKVgQhn2tMG6axJH+vQgvD5JLgPnYL49GhpzXNdpX7jCQAmMKwfFVy9voBpqyoJGy2BeoUd/7+C7JMRESKjsPB9D8UFFiIboKsrwQfn8hqhqGCSJfyKpLoDdpbg4dE02malBEbUm3uOHaR235jfZHqpQI77kseFXXz2KVJhLDamj2CPd3VAB6W8CUaUxMPfwISuVhGcxNXSLrZNJ4LNOzdPhla8JNYqW2KfmXgO5cBACzhXGb0UmfRkVr+ReJ+WootxbcuztqSJML8eA3h/rpR9TvU3DpFZn2caea/TFSybP+bRCS+mPpdCXG7qfHjEFd1IP3v2BGlpuxhrG4wway8ciX5lSb5GUlu1d3V1P5C33Etc4PLeZ/v3CsZWDfasTLxjoQjwAnqfIPQFZkkK4IyEuy5fclg3F5YXe0KRKpPMD1vzPBdrkUNIUtQ9dWMdx78=
