language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8
before_install:
- git checkout main
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: tsukada-cs
  password:
    secure: MnyIiaND1w3U6E3ZeG1USt00L/99a7gKt33t9eyDcEKYAxU/O3CHju1D9lV23zOH29JldqYqq+JvsIPNkMiu2D6ejfm8nppWkVfj12VBt2+VJJ0BLqgudYS608ee2oQgtVehrOs+oFhigRnpajGJ7SObCyWgyBZ7VQa++o5GbFQv8KEW9zmGpODc1FVS/1a1FYNMJz09EkO4DdndLsgUzXQD1C2fQL8wvBs09Ax14K4EpNopwCOloZh+VlkVEPwKLio1zyfIy1qYAimGgkiaotZ173TLvnqmv26SV9EV7O1juKnndW+uzkvneSIteKCrFJ8r0/0BkhC50kDRsS8rzonwTtUFiBiHwH0pWBG2zuTe3x5lQjFVf5iUajvk4y9F6soAWhLrjzZTkj+BvdKo5VjPVAQI+DfGBM6caV68gSNhuF473LjXkgtVuN/JKIvGC3gi9D6XNsd+32/iog/O2HNAVElVJlvykMj2SQ4XNObj0sgJpGkrtIDxeBwxof0i5ArnJUbDKVQgZ617LOIjC77992TyvpHq80fzvCfxcNsTWdgHQ2LFpc9nazkzuNIDdESN4/HlChBKLSecEBSWV3v6J9Dx2vI27o5Wfm+1QBDzP83KFYmZJUG+PyaGRjLPcb5x/fW6W9+QDi2QkqZlyhw2rp/bCC0r/zhrOQcmQDQ=
  distributions: sdist
  skip_existing: true
  on:
    repo: tsukada-cs/pyfld
    branch: main
    python: 3.8
