language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8
before_install:
- git checkout main
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: tsukada-cs
  password:
    secure: OMB5YldVoaMeZhl/kf/RWfYga6f3KHBQeuZ40GL7jLEDLA6aHRT7YYc6gXe2jSDcOX+KrMl9F8I+LZW0ZTbyheiorlzAjQPpmR8x7jswzWT1YEr6kp0d61zdmgNi/ul6Xcgi4lldDr3SU5tf7565e5vRgtcahNLyqeIe+kw5Z2IotPN5hKx4ftiP80h3VtoL/upSI2qzB3mz2rNlD0B8EbStJ1ty0tR//NFZnr+QrItM25FlVgWlGSr3TUhFrAZhxZURN3XOTFjs3gm1DjG674ItyGbSJ41TRQhis5nE1a0cyxlTPyIWbM9fne7cywEeaw91v5me6B1ajTXajx7lgVJzZyWP4bie6SS8NnyjFGFxWym6zIvk+ukJxf18MPkYy1kYcvF6jTP6p5UmHimY1F0PPquykOiwEQxjS+HMC41APvs8z5Ky7sJFzclEe5Ea7n5TBjLeNY18FYSM7TLwrMfePjSj5KFqWAW+Ja0gMfWSPR7uj7nAB90dOqNFdjUmPYd7HUjwSHl600t2wrwvWvUa0Ceoxq8uSYEk3y97IEB4MBRmLKGut+a7EM0j5HDdPsrEfL1nNSqyB55UG2h1bKu3uqoQafC5bC0mNEG7MABUU9xCIZbZXjiJ6QqfEWtHONH7bw2VGju3TK7hQlplv1nNn/T5bYhBz+HHmI2lDl0=
  distributions: sdist
  skip_existing: true
  on:
    repo: tsukada-cs/pyfld
    branch: main
    python: 3.8
