language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8
before_install:
- git checkout main
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: V/2HWV3BNl4Go18U4TjA3+5ln91ubz1ptqj4D9c7sd3hIKRFd4ynI0IxXx4hUPT+U7eA28t1Z3OVrNjh+SvtDt2PEchJUA+hBDT/dpFJIZoBV4V1xToUGJg6+VzZzV/Of6TmcFW+8U+gFvEksQEiEO+4nWTlsKgU/SBam55j/rHg6U+5+I0oAgzh9X6SB0IRwR6cyCFn9QKL+VUpCDK0x6TNvXnxf0lC30J1QzFIt6ZdeANMHRDRwLu4ZOG37S9oW1MZ9DDw/XfkVIT7BTbqR72ppTNZ5Ly8mM4zRhQCmFo7BKVO4sjCiZgjx6gPtlNK7c3PKJpmOf8g2K73lTI3l4JKo8ck1c12Di8Dt7tPu+OCGFtmq20Cpn8/WodtXdnJ5Jc3+ImBo8wmF4yQcJ84NjR5ij5h/Nq5l5huU1b6rkjCyfAdpH06i0aIjPxsQ9VYjNcWctgbL1RAcx0aZSs3MF7ZE7HjSRUd3x/1tVwaugVGXkOA6YdUELWBvD2Yzl3evTKkB5YfH1p5Dwu2wiBi7xJD9v8mHiAi3Ciu526A85yX4UMELYKMAzUOh3TfAoWj84hmbzbnQGVyzW3JcZaypTxNkx1SEdTzhGKdUveFhsa6g8ht80zdQucQT43jaM0ulYix2f5/agQPttWGRnKZdjq3gTP7k4dWo5ODaH4N2Zg=
  distributions: sdist
  skip_existing: true
  on:
    repo: tsukada-cs/pyfld
    branch: main
    python: 3.8
