language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8
before_install:
- git checkout main
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: QBTUM26PtSVxfancHfB5nXiXI6bkWeFh+QbYyFlodDyTvzVfQaxvyoiZ3cCFqqMfJ0IrF1ZSAtzbcSxIKWlg65CrknrXaD1wi2c+i5qcdpbkqYGwyo0iUVRUBny3hF7CuBvkxp44YB5uglb38C/aJdpMaWmjXC44zVtATDglkXsNbwLB85mNcIf3ItwpqVFV7J4Zr3IfJmMtVtR8XiYNYKZg2ler+9O6hEF1Yn3kNHmzKbru/TV6qgtUy2xVjbSqyFRNNvFblr0RhILgh1BBIlyGpdu4fYX6t8LClqs8cPPeHSjj/SymhQlxdzfy5OcgDjTnZGXTwD981ipzBDYJ9mtc3XeMrSpz3MEeretrN0m1M0x3wF56BKgKyWNQkdsQ+MvNtUTHwtpBMt4/Bk3Zr7Z2fMCClkMq0sZU2eRegSoPFJ6MoiI4JmW1UgnKwU7hqI2nB6LehEYj7i+vnR7dJVNZMO7djlZk+pq4foVcCdvFStU95KFe0nIgf98EaCfJAcQziVFSD3ciufU27nFr6z/OQTBExoW/aAtVy19getdTxwY05kCFGJXxqjBcZzkFTxkKVdvSHuIJCq/HB0xgWtK/5heESq0UsNuuHA4ZyLfYGlYtVoOi6KVl9bNV7fuWXu4bS2irFOEPdOtQi0dza9FJtUcX264TnOXWU++TmxA=
  distributions: sdist
  skip_existing: true
  on:
    repo: tsukada-cs/pyfld
    branch: main
    python: 3.8
