language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8
before_install:
- git checkout main
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: tsukada-cs
  password:
    secure: iU4/17V89NzTp+e56ACN4pahYS97UpBlXubYxcFzUBXekDc8e5YJKcKBUOqjWGKDmd+lEx0gpq/HonyXPtfsts1CS4XWMuTVXMeuwp9Em0d3Z69n1scV0UJXH6TR0xAuiL8VsDitJJokH6SifJF13dzYO3OnhGrmwVSyFTzru405RUObdykVNo/WcVBcyJKzzbbv/rvVQKkI/9+n44qpR2V+w/mBrQi2Jsxgm7ZrOxWmQ91T0Ca3wgQJO8qiCmRx6KqK7bNQbvLp0KjU3jJjsWOqWOZv7QPiEME9+alR59b2h/rj1w6ycbddusJPhz0317t6aNyArcQImowz8VFyvK2ORRYQUCz+r7tyOru9tNsv2b+CktlPsa+ldENqh3gq/csUajnddtEk0xeQTRGDCPdrRbYbtgCPsvQMhPyhpTm5reXKfsbNd/PcIRH/O0rdghf+TcP299iI2avso8fp7iDnXQKqWlmEoxoPQ/9H0qcyvhWA7XT7IytPz6oWeko8l/nmKJ1QHtPd/jIDP+MjhEjnQIJAxwT/JFtyFw8Crnnhp4iqarNVDzPE5tloyYlX1cqVJmovvlXchgoOp6GGGXsONhhUYTdJ8oCJZ+PfQEYU+C8In9DyySfEutUiFOYKuvywT2SDXdSZ+1F8P0z2FyzEqn+IIjpOjIjyJU1wZLE=
  distributions: sdist
  skip_existing: true
  skip_cleanup: true
  on:
    repo: tsukada-cs/pyfld
    branch: main
    python: 3.8
dd:
  secure: MAWZUCylYqeqzkabtKh7Gb1RbtGfzwi9ZwWgNz+6MIL/6psJ3bb3X7tqVEFRl6FoG3hFs/OoH7AG/EyPfJA81ZIbffOFgnlZj+5Q7k+9Z8+82hxsZ6eDLn4+lSuKPxLF/Ml+09XQ66Ktz7mDnQZpZ3aMvNbUHzif8HYgme7ia4HzUnooqE7gcbMHhJcGWM4MDltkWVpDWnmF9OM7AkvuLiWllyLfQIWYYF+YSg00LicRkinRYsEy/kAybQZTSZVvB993fTYmzatFb/IIolLTkBcILwQ0nBkRdoFlPTREnLYdcVl67mlok7HGr+LDifQPlOhE29bhGtV4ChQQV8eayxuHkfzEFsKnF6FBBCC/pFNQ8hl3YMH/NRchDVIDBBVxJ3vvAqf2nLrWL3HF7Pu8cFA0mrX2uasen1y6PlaMUyWAskJtEQX73ieIApaR+uoOBr1jhz2W48TScqdCE2c0hVUBEhtDCQEktom2tMH/snajgcAsBTl1NHxRJ5NYW9EzjN/AZ3vL+VSrIjVofgx9Ppl22PNqn4PRXSqNtx3SV+vdsyvV1k5rLU2XkBKnmD1rAquq1wqj7ksxcIKRuhEiTdlmslO4386jtat38mw20SjDNbCgzfrRr7V+mnZRcR2Cx9Zm7M9WkxSON/Xp59ueVfdzFU0EfbGwCpM92cA2wT8=
