language: python
os:
- linux
python:
- 3.6
- 3.7
- 3.8
before_install:
- git checkout main
- pip install coveralls pytest-cov
install:
- pip install -e .
script:
- pytest --cov=pyfld pyfld/tests
- coverage run -a --source=pyfld -m pytest pyfld/tests
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password: pypi-AgEIcHlwaS5vcmcCJGQ1NjNiM2IwLTk3MGMtNDg5NC05YmI5LTgzZjAyOTJmNDI0ZAACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgrzP11OLU3twJ6D9NDCxkSREFlEtwcGNtMtXc4hOH8TQ
  distributions: sdist
  skip_existing: true
  on:
    repo: tsukada-cs/pyfld
    branch: main
    python: 3.8
